### ISSUE TITLE
Package/codebase name 

### ISSUE THREAD

**Issue by Tiriyon** [Vanilla-OS/Prometheus#6]
Hey,
Came to look around out of curiosity. Found this repo, which seems to be part of an auxiliary tool for the Vanilla OS package manager. I wonder why is it called Prometheus, since there is already a major monitoring tool, [Prometheus](https://prometheus.io/), which is loosely coupled with the branch of containers through Kubernetes. I think that might come as confusing.

**Comment by mirkobrombin** [comment]
We use to give Greek names to the majority of our core components and libs: https://github.com/Vanilla-OS/Prometheus#why-the-name-prometheus

**Comment by taukakao** [comment]
I think the difference is pretty clear if you read the description. 
The other Prometheus is definitely not a "library for pulling and mounting container images".
